services:
  db:
    image: postgres:14
    container_name: courtcosts_db
    restart: always
    environment:
      POSTGRES_DB: courtcosts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: courtcosts_web
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    command: ["sh", "entrypoint.sh"]

  frontend:
    build:
      context: ../../frontend/courtcosts-frontend
      dockerfile: Dockerfile
    container_name: courtcosts_frontend
    ports:
      - "3000:3000"
#    volumes:
#      - ../../frontend/courtcosts-frontend:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]

volumes:
  postgres_data:
