services:
  db:
    image: postgres:14
    container_name: courtcosts_db
    restart: always
    environment:
      POSTGRES_DB: courtcosts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: courtcosts_web
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    command: [ "sh", "entrypoint.sh" ]

volumes:
  postgres_data:
